### ISSUE TITLE
Is it possible to skip bumping the version if the version in version.txt is the same as the project version?

### ISSUE THREAD

**Issue by yingtao-butterflymx** [yanamura/ios-bump-version#17]
Is it possible to skip bumping the version if the version in version.txt is the same as the project version?
Thank you!

**Comment by yanamura** [comment]
@yingtao-butterflymx  if you want to run this GitHubActions when version.txt is changed, how about this setting?
```
on:
  push:
    paths:
      - 'version.txt'
```
